name: CI-CD Deploy To K8s

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show environment
        run: |
          whoami
          kubectl get nodes
          docker version

      - name: Build image
        run: |
          docker build -t hello-devops:${{ github.sha }} .

      - name: Import image into k3d
        run: |
          k3d image import hello-devops:${{ github.sha }} -c dev

      - name: Deploy new image
        run: |
          kubectl set image deployment/hello-devops \
          hello-devops=hello-devops:${{ github.sha }}

      - name: Inject version into pod
        run: |
          kubectl set env deployment/hello-devops \
          APP_VERSION=${{ github.sha }}

      - name: Wait rollout
        run: |
          kubectl rollout status deployment/hello-devops
